#!/usr/bin/env bash

if [[ $1 == "" ]]; then
	exit 1
fi

case $(($RANDOM % 3)) in
	0) TYPE=wipe ;;
	1) TYPE=grow ;;
	2) TYPE=any ;;
esac

swww img $1 --transition-angle 45 --transition-step 8 -t $TYPE
